### ISSUE TITLE
The jenkins-mesos service disappears from the Mesos dashboard

### ISSUE THREAD

**Issue by rupakg** [mesosphere/jenkins-mesos#22]
After installing the jenkins-mesos package with DCOS, the Jenkins service shows shows up under services on the Mesos dashboard.

The problem starts as soon as I configure something Jenkins via Jenkins UI (install plugins etc.) and restart jenkins. The jenkins service disappears from the Mesos dashboard.

**Comment by ssk2** [comment]
Hi @rupakg - I suspect you're using an older configuration. Can you share what version of the package you have installed via `dcos package list`?

**Comment by rupakg** [comment]
@ssk2 below

jenkins      0.1.2      /jenkins-paas

**Comment by ssk2** [comment]
Looks like upgrading your Jenkins fixed this!

**Comment by rupakg** [comment]
@ssk2 thanks a lot for helping on this issue.
