### ISSUE TITLE
curl broken in 0.2.0

### ISSUE THREAD

**Issue by mikestaub** [mesosphere/jenkins-mesos#50]
I am running DCOS 1.5.2, I ran

`dcos package install jenkins`

It works well, but when I try to run curl commands in my jenkins jobs I get this error:

`curl: /opt/mesosphere/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by curl)`

**Comment by ssk2** [comment]
Hey @mikestaub - are you using the Docker slave image (`jenkins-dind`) that we preconfigure? I can't replicate the issue with curl inside this container or on a running cluster.

Alternatively, what kind of URL are you trying to get? I've tested with both https and http and can't see an immediate issue.

**Comment by mikestaub** [comment]
Sorry, this was a user error. I was accidentally running my jenkins job on the master because I had the executors set to 1.

**Comment by ssk2** [comment]
Ah, phew :). Glad it's working!
