### ISSUE TITLE
file not find

### ISSUE THREAD

**Issue by zhwenh** [mesosphere/jenkins-mesos#58]
/usr/lib/x86_64-linux-gnu/libsvn_delta-1.so.1 file not find
/opt/mesosphere/lib/ has libmesos-0.27.0.so
libload_qos_controller.so libmesos.so .....
open first page show error
Caused by: java.lang.UnsatisfiedLinkError: no mesos in java.library.path
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)

**Comment by ssk2** [comment]
Hi @zhwenh - what version of DCOS are you using?

**Comment by zhwenh** [comment]
dcos version 0.3.5

**Comment by ssk2** [comment]
That's the version of the DCOS CLI - what about your DCOS installation itself? You can view this from the user interface, on the left hand side.

**Comment by zhwenh** [comment]
Mesos and marothon is myself through the RPM package installed, no dcos deployment, I just use DOS cli even marothon deploy Jenkins framwork

**Comment by ssk2** [comment]
Unfortunately we've only tested this against DCOS itself and the package itself makes assumptions that you're running on DCOS. As such, it won't work very well against just Mesos + Marathon.

I'll update the documentation to reflect this!
