### ISSUE TITLE
slow jenkins tasks

### ISSUE THREAD

**Issue by mikestaub** [mesosphere/jenkins-mesos#68]
We are using this DCOS package and it works just fine, but I have noticed one limitation that I think is worth discussing.

Because the jenkins mesos tasks are running Docker-in-Docker, they cannot cache any of the docker images. In our tests, we have to create a new image every time to run our tests against it, and this can take up to 15 minutes for a large image to build from scratch.

What are some ways to get around this?

Perhaps we could pull the previous image and then just mount the current source as a volume to save some time, but if the image itself changes the test is not technically a valid one.

I guess this is related to docker testing in general, and I'm curious to hear how other people are testing their docker images in jenkins.

**Comment by ssk2** [comment]
Hey @mikestaub, unfortunately we don't have a better solution at the moment. In the future Mesos will hopefully have features that allow us to correctly account for sibling containers without having to run Docker in Docker. This should see a return to the caching behaviour you're used to :).

**Comment by mikestaub** [comment]
Good to know thanks. I guess for now I'll just have to accept the long build times.

**Comment by ssk2** [comment]
Are you running a local registry by the way? That might save a small amount of time.

**Comment by pdiniz13** [comment]
Has there been any update on this? The slow build times is the only thing keeping us from using Jenkins on mesos.

**Comment by ssk2** [comment]
@pdiniz13, we're working with the Mesos team to come up with a better solution that avoids having to use Docker in Docker and is able to track "sibling" containers. This will allow us to re-use the Docker cache on the host machine and avoid the "orphaned container" problem. Exact implementation details are still being worked out at the moment. Realistically, I suspect this will make it into the DC/OS 1.9 or 1.10 release.
