### ISSUE TITLE
Questions: Persistent Storage for Jenkins_home

### ISSUE THREAD

**Issue by hanken** [mesosphere/jenkins-mesos#73]
Hi

We're running the DCOS CE and would like to use jenkins with it. But how can we have a persistent store for the jenkins data? We tried with hdfs and exposed it via a NFS share that we mount on every slave. But unfortunately this does not work at all. 

Any advice or hints to resources would be greatly appreciated?  

Thank you

**Comment by ssk2** [comment]
Hi @hanken, are you running on AWS? 

For now, we recommend pinning it to one machine and setting up backups for that machine. This is the config option to set: https://github.com/mesosphere/universe/blob/version-2.x/repo/packages/J/jenkins/7/config.json#L55

Amazon's EFS may also be another option but this is in preview currently. We haven't had a chance to test this yet. We may also soon be providing a distributed file system as part of DCOS that is POSIX compatible - but no timeline on this just yet!
