### ISSUE TITLE
No 'Marathon Deployment' option in 'Add post-build action' drop-down in configure page

### ISSUE THREAD

**Issue by alexraju** [mesosphere/jenkins-mesos#75]
I have added the Jenkins service from DC/OS universe. I'm facing a certain issue while trying to deploy a successful build to Marathon in Jenkins. I'm following  https://docs.mesosphere.com/usage/services/velocity/marathon-deployment-on-velocity-walkthrough/ for this. I'm stuck at the Marathon deployment. There is no 'Marathon Deployment' option under 'Post-build-action' drop-down as explained in the walk-through post. Could you please help to resolve this.

I've created a job to checkout from git, build docker image and push to dockerhub. The build is running fine. There is no other issue except the Marathon deployment.

**Comment by ssk2** [comment]
Hi @alexraju - that's actually for a different product which is currently only available to Mesosphere customers and early access users. You can manually install the Marathon plugin to provide the deployment post build action from https://github.com/mesosphere/jenkins-marathon-plugin/releases.
