### ISSUE TITLE
Exposing the jenkins webhook

### ISSUE THREAD

**Issue by pdiniz13** [mesosphere/jenkins-mesos#82]
Whats the process for exposing the jenkins webhook. I'm trying to deploy on azure and the only way ive been able to do so has been to expose port 80 of master in order to reach dcos and by extension the /service/jenkins port. I won't be able to leave it open because it leaves the entire dcos admin page exposed. What are the alternatives?

**Comment by ssk2** [comment]
Hey @pdiniz13, unfortunately you will need to expose Jenkins publicly in order to accomplish this but you should be able to avoid exposing your entire DC/OS cluster. 

What we do, for our instance, is use Marathon-lb to expose this (by setting the `HAPROXY_0_VHOST` variable to a virtual host, and pointing that virtual host to the public nodes that Marathon-lb is running on). We then use existing Jenkins authentication features to limit access by anonymous users. This'll make Jenkins publicly accessible at the VHOST hostname.  Note that when you do this, you won't be able to use the link in the DC/OS dashboard to access Jenkins directly anymore.

**Comment by pdiniz13** [comment]
I did set up the haproxy_0_vhost, but thats the same virtual host that dc/os is exposed at so by allowing the 80 connection to the virtual host dc/os becomes exposed.

**Comment by ssk2** [comment]
@pdiniz13 I'm not hugely familiar with the Azure templates, let me see if I can figure that out. On Amazon, the public nodes operate behind an ELB which is separate to that of the DC/OS masters.

**Comment by pdiniz13** [comment]
as far as i understand it, azure does the same. But my public node is already mapped to my main application which is running on it. Is it possible to map jenkins to another port on that VHOST.

**Comment by ssk2** [comment]
What we typically do is deploy Marathon-lb on the public nodes and then give _all_ applications a VHOST. In this case, you could add a different VHOST to your main application's Marathon definition and let Marathon-lb selectively route to either of those. 

Alternatively, you can run Marathon-lb on the public node and set it not to bind to http/https in the [configuration](https://github.com/mesosphere/marathon-lb/blob/master/Longhelp.md#other-labels). Jenkins will be served up at a fixed service port (which you can set in the Marathon definition for the Jenkins service). For example: http://my-public-node:10000.

**Comment by pdiniz13** [comment]
Azure apparently doesn't [allow](https://azure.microsoft.com/en-gb/documentation/articles/load-balancer-multivip/) multiple vip's in this case. But we are using route53 to handle out domain name, so I was able to add the vhost there, and its now working. Thank you for the help.

**Comment by ssk2** [comment]
Excellent!

**Comment by lihengzkj** [comment]
Hi @pdiniz13, can share me details what did you do to expose Jenkins. I am using DCOS and want config Jenkins to auto build my project when the project code changed. I tried webhook on github, but failed. then config in Jenkins which run on dcos, but still failed. so i think i need your help. thanks.

**Comment by ssk2** [comment]
@lihengzkj are you using Marathon-lb with Jenkins?

**Comment by lihengzkj** [comment]
@ssk2 my jenkins is not expose to Marathon-lb.
I think it should be work on marathon-lb, i am trying to config a vhost for jenkins, and make jenkins work on public agent, then I can access it bypass dcos.

**Comment by pdiniz13** [comment]
```{
  "volumes": null,
  "id": "/jenkins",
  "cmd": null,
  "args": null,
  "user": null,
  "env": {
    "LD_LIBRARY_PATH": "/opt/mesosphere/lib",
    "SSH_KNOWN_HOSTS": "github.com",
    "JENKINS_CONTEXT": "/service/jenkins",
    "JENKINS_AGENT_ROLE": "*",
    "JVM_OPTS": "-Xms1024m -Xmx1024m",
    "JENKINS_ROOT_URL": "http://jenkins.host.com/service/jenkins",
    "JENKINS_MESOS_MASTER": "zk://leader.mesos:2181/mesos",
    "JENKINS_AGENT_USER": "root",
    "JENKINS_OPTS": "",
    "JENKINS_FRAMEWORK_NAME": "jenkins"
  },
  "instances": 0,
  "cpus": 1,
  "mem": 2048,
  "disk": 0,
  "gpus": 0,
  "executor": null,
  "constraints": null,
  "fetch": null,
  "storeUrls": null,
  "backoffSeconds": 1,
  "backoffFactor": 1.15,
  "maxLaunchDelaySeconds": 3600,
  "container": {
    "docker": {
      "image": "mesosphere/jenkins:2.1.0-2.19.3",
      "forcePullImage": false,
      "privileged": false,
      "network": "HOST"
    },
    "type": "DOCKER",
    "volumes": [
      {
        "containerPath": "/var/jenkins_home",
        "hostPath": "/mnt/data/jenkins/jenkins",
        "mode": "RW"
      },
      {
        "containerPath": "/opt/mesosphere",
        "hostPath": "/opt/mesosphere",
        "mode": "RO"
      }
    ]
  },
  "healthChecks": [
    {
      "protocol": "HTTP",
      "path": "/service/jenkins",
      "gracePeriodSeconds": 30,
      "intervalSeconds": 60,
      "timeoutSeconds": 20,
      "maxConsecutiveFailures": 3,
      "ignoreHttp1xx": false
    }
  ],
  "readinessChecks": null,
  "dependencies": null,
  "upgradeStrategy": {
    "minimumHealthCapacity": 0,
    "maximumOverCapacity": 0
  },
  "labels": {
    "DCOS_PACKAGE_RELEASE": "15",
    "DCOS_SERVICE_SCHEME": "http",
    "DCOS_PACKAGE_SOURCE": "https://universe.mesosphere.com/repo",
    "HAPROXY_GROUP": "external",
    "DCOS_PACKAGE_METADATA": "=",
    "DCOS_PACKAGE_REGISTRY_VERSION": "2.0",
    "DCOS_SERVICE_NAME": "jenkins",
    "DCOS_PACKAGE_FRAMEWORK_NAME": "jenkins",
    "DCOS_SERVICE_PORT_INDEX": "0",
    "DCOS_PACKAGE_VERSION": "2.1.0-2.19.3",
    "DCOS_PACKAGE_NAME": "jenkins",
    "MARATHON_SINGLE_INSTANCE_APP": "true",
    "DCOS_PACKAGE_IS_FRAMEWORK": "true",
    "HAPROXY_0_VHOST": "jenkins.host.com"
  },
  "acceptedResourceRoles": [
    "*"
  ],
  "residency": null,
  "secrets": null,
  "taskKillGracePeriodSeconds": null,
  "portDefinitions": [
    {
      "protocol": "tcp",
      "port": 10000
    },
    {
      "protocol": "tcp",
      "port": 10001
    }
  ],
  "requirePorts": false
}```

this is the config file
